blank_issues_enabled: false
contact_links:
  - name: Poser une question
    url: https://github.com/dimtrovich/php-db-dumper/discussions/new?category=q-a
    about: Demandez de l'aide à la communauté
  - name: Demander une fonctionnalité
    url: https://github.com/dimtrovich/php-db-dumper/discussions/new?category=ideas
    about: Partagez des idées de nouvelles fonctionnalités
  - name: Signaler un problème de sécurité
    url: https://github.com/dimtrovich/php-db-dumper/security/policy
    about: Découvrez comment nous signaler les bugs sensibles